# R code to generate simple generation plots from *.p files generated by mrbayes
# Pablo Vinuesa  @pvinmex
# CCG-UNAM, Morelos, Mexico
# https://www.ccg.unam.mx/~vinuesa/
# Diplomado en Bioinformática, UAS, october 2021
# https://github.com/vinuesa/intro-filoinfo_UAS


# execute the following lines from an R console or from within an RStudio session

f1r1<-read.table("primates4bayes.nex.run1.p", skip=1, header=T)
f1r2<-read.table("primates4bayes.nex.run2.p", skip=1, header=T)

pdf(file="primates4bayes_generation_plots.pdf")
plot(f1r1[,2], type="l", col="blue", xlab="No. of generations", ylab="lnL", main="Pre-burnin generation plots for runs 1 & 2")
points(f1r2[,2], type="l", col="red")
legend("bottomright", lty=c(1,1), col=c("blue", "red"), c("run1", "run2"))

plot(f1r1[50:500,2], type="l", col="blue", xlab="No. of generations", ylab="lnL", main="Post-burnin generation plots for runs 1 & 2")
points(f1r2[50:500,2], type="l", col="red")
legend("bottomleft", lty=c(1,1), col=c("blue", "red"), c("run1", "run2"))
dev.off()
quit()
